name: Info Bot
on:
  pull_request_target:
    types: [opened, reopened, synchronize]


jobs:
  Auto_Comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
