name: Info Bot
on:
  pull_request_target:
    types: [opened, reopened, synchronize]


jobs:
  Auto_Comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Commment 
        uses: NejcZdovc/comment-pr@v1
        with:
          file: "test.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
